const IOComponents = {
  led: { output: true, input: false },
  laser: { output: true, input: false },
  beeper: { output: true, input: false },
  geared_motor: { output: true, input: false },
  mini_geared_motor: { output: true, input: false },
  motor_driver: { output: false, input: false },
  servo_motor: { output: true, input: false },
  dc_motor: { output: true, input: false },
  servo_extender: { output: true, input: false },
  mp3: { output: true, input: false },
  "7segment_display": { output: true, input: false },
  "4_CH_relay": { output: true, input: false },
  stepper_motor: { output: true, input: false },
  //'relay' : { output: true, input: false },
  electromagnet: { output: true, input: false },
  led_strip: { output: true, input: false },
  dot_matrix: { output: true, input: false },
  dual_splitter: { output: true, input: false },
  octa_splitter: { output: true, input: false },
  light_sensor: { output: false, input: true },
  bend_sensor: { output: false, input: true },
  gas_sensor: { output: false, input: true },
  distance_sensor: { output: false, input: true },
  sound_sensor: { output: false, input: true },
  temperature_sensor: { output: false, input: true },
  humidity_sensor: { output: false, input: true },
  hall_sensor: { output: false, input: true },
  metal_detector: { output: false, input: true },
  ultrasonic_sensor: { output: false, input: true },

  rotatory: { output: false, input: true },
  heartbeat_sensor: { output: false, input: true },
  rfid: { output: false, input: true },
  color_sensor: { output: false, input: true },
  rain_sensor: { output: false, input: true },
  tact_switch: { output: false, input: true },
  dual_switch: { output: false, input: true },
  joystick: { output: false, input: true },
  touch_sensor: { output: false, input: true },
  pir_sensor: { output: false, input: true },
  gesture_sensor: { output: false, input: true },
  "4_in_1_sensor": { output: false, input: true },
  gyro_sensor: { output: false, input: true },
  rotational_sensor: { output: false, input: true },
  accelerometer: { output: false, input: true },
  solar_panel: { output: false, input: true },
  battery: { output: false, input: false },
  compass: { output: false, input: true },
};

module.exports = IOComponents;
