// var Device=JSON.stringify(sessionStorage.getItem("connectedDevice"));
var Device = sessionStorage.getItem("connectedDevice");

if (Device == "Ace") {
  module.exports = {
    A: { color: "red", ports: ["A"] },
    B: { color: "red", ports: ["B"] },
    C: { color: "red", ports: ["C"] },
    D: { color: "red", ports: ["D"] },
    A1: { color: "green", ports: ["A1"] },
    B1: { color: "red", ports: ["B1"] },
    C1: { color: "green", ports: ["C1"] },
    D1: { color: "green", ports: ["D1"] },
    A2: { color: "red", ports: ["A2"] },
    B2: { color: "red", ports: ["B2"] },
    C2: { color: "red", ports: ["C2"] },
    D2: { color: "green", ports: ["D2"] },

    STPM: { color: "yellow", ports: ["STPM"] },
  };
} else if (Device == "Humanoid") {
  module.exports = {
    A: { color: "RED", ports: ["A"] },
    B: { color: "RED", ports: ["B"] },
    C: { color: "RED", ports: ["C"] },
    D: { color: "RED", ports: ["D"] },
    A1: { color: "white", ports: ["A1"] },
    B1: { color: "white", ports: ["B1"] },
    C1: { color: "white", ports: ["C1"] },
    D1: { color: "white", ports: ["D1"] },
    A2: { color: "white", ports: ["A2"] },
    B2: { color: "white", ports: ["B2"] },
    C2: { color: "white", ports: ["C2"] },
    D2: { color: "white", ports: ["D2"] },
  };
} else {
  module.exports = {
    A: { color: "white", ports: ["A"] },
    B: { color: "white", ports: ["B"] },
    C: { color: "white", ports: ["C"] },
    D: { color: "white", ports: ["D"] },
    E: { color: "white", ports: ["E"] },
    F: { color: "white", ports: ["F"] },
    G: { color: "white", ports: ["G"] },
    H: { color: "white", ports: ["H"] },
    I: { color: "white", ports: ["I"] },
    // M: { color: "white", ports: ["M1", "M2"] },
    A1: { color: "white", ports: ["A1"] },
    B1: { color: "white", ports: ["B1"] },
    C1: { color: "white", ports: ["C1"] },
    D1: { color: "white", ports: ["D1"] },
    E1: { color: "white", ports: ["E1"] },
    A2: { color: "white", ports: ["A2"] },
    B2: { color: "white", ports: ["B2"] },
    C2: { color: "white", ports: ["C2"] },
    D2: { color: "white", ports: ["D2"] },
    E2: { color: "white", ports: ["E2"] },
    F1: { color: "white", ports: ["F1"] },
    F2: { color: "white", ports: ["F2"] },
    G1: { color: "white", ports: ["G1"] },
    G2: { color: "white", ports: ["G2"] },
    H1: { color: "white", ports: ["H1"] },
    H2: { color: "white", ports: ["H2"] },
    I1: { color: "white", ports: ["I1"] },
    I2: { color: "white", ports: ["I2"] },
    MOTOR: { color: "white", ports: ["MOTOR1", "MOTOR2"] },
    MOTOR1: { color: "white", ports: ["MOTOR1"] },
    MOTOR2: { color: "white", ports: ["MOTOR2"] },

    // 'A': { color: "white", ports: ['A1', 'A4'] },
    // 'A23': { color: "white", ports: ['A2', 'A3'] },
    // 'MOTOR': { color: "white", ports: ['MOTOR1', 'MOTOR2'] },
    // 'BC': { color: "white", ports: ['BC'] },
    // 'B': { color: "white", ports: ['B'] },
    // 'C': { color: "white", ports: ['C'] },
    // 'F': { color: "white", ports: ['F'] },
    // 'G': { color: "white", ports: ['G'] },
    // 'F12': { color: "white", ports: ['F12'] },
    // 'BATTERY': { color: "white", ports: ['BATTERY'] },
    // 'F1': { color: "white", ports: ['F1'] },
    // 'F2': { color: "white", ports: ['F2'] },
    // 'G1': { color: "white", ports: ['G1'] },
    // 'G2': { color: "white", ports: ['G2'] },
    // 'B12': { color: "white", ports: ['B12'] },
    // 'B34': { color: "white", ports: ['B34'] },
    // 'C12': { color: "white", ports: ['C12'] },
    // 'C34': { color: "white", ports: ['C34'] },
    // 'B1': { color: "white", ports: ['B1'] },
    // 'B2': { color: "white", ports: ['B2'] },
    // 'B3': { color: "white", ports: ['B3'] },
    // 'B4': { color: "white", ports: ['B4'] },
    // 'C1': { color: "white", ports: ['C1'] },
    // 'C2': { color: "white", ports: ['C2'] },
    // 'C3': { color: "white", ports: ['C3'] },
    // 'C4': { color: "white", ports: ['C4'] },
    // 'A22': { color: "white", ports: ['A22'] },
    // 'A33': { color: "white", ports: ['A33'] },
  };
}
